alter table public.hermes_messages
  add column if not exists message_seq bigint generated by default as identity;

create index if not exists idx_hermes_messages_conv_message_seq_desc
  on public.hermes_messages (conversation_id, message_seq desc);
